# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from word_segmentor import SentenceSplit_pb2 as SentenceSplit__pb2


class sendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.split = channel.unary_unary(
        '/nlp.split.send/split',
        request_serializer=SentenceSplit__pb2.splitRequest.SerializeToString,
        response_deserializer=SentenceSplit__pb2.splitResponse.FromString,
        )


class sendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def split(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_sendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'split': grpc.unary_unary_rpc_method_handler(
          servicer.split,
          request_deserializer=SentenceSplit__pb2.splitRequest.FromString,
          response_serializer=SentenceSplit__pb2.splitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nlp.split.send', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
