# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SentenceSplit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SentenceSplit.proto',
  package='nlp.split',
  syntax='proto2',
  serialized_pb=_b('\n\x13SentenceSplit.proto\x12\tnlp.split\"D\n\x0csplitRequest\x12\x0c\n\x04text\x18\x01 \x02(\t\x12&\n\x06params\x18\x02 \x01(\x0b\x32\x16.nlp.split.SplitParams\"*\n\rsplitResponse\x12\x0c\n\x04word\x18\x01 \x03(\t\x12\x0b\n\x03pos\x18\x02 \x03(\t\"\xdd\x02\n\x0bSplitParams\x12\x18\n\tkeep_punc\x18\x01 \x01(\x08:\x05\x66\x61lse\x12!\n\x16\x65ng_word_len_threshold\x18\x02 \x01(\x05:\x01\x30\x12\x16\n\x08need_pos\x18\x03 \x01(\x08:\x04true\x12\x19\n\x0b\x61uto_rec_nr\x18\x04 \x01(\x08:\x04true\x12\x1d\n\x0frec_long_entity\x18\x05 \x01(\x08:\x04true\x12\"\n\x14rec_ambiguous_entity\x18\x06 \x01(\x08:\x04true\x12\x1e\n\x10need_term_weight\x18\x07 \x01(\x08:\x04true\x12*\n\x1equotation_entity_len_threshold\x18\x08 \x01(\x05:\x02-1\x12\x1f\n\x11recognizer_entity\x18\t \x01(\x08:\x04true\x12.\n#quotation_common_word_len_threshold\x18\n \x01(\x05:\x01\x33\x32\x44\n\x04send\x12<\n\x05split\x12\x17.nlp.split.splitRequest\x1a\x18.nlp.split.splitResponse\"\x00')
)




_SPLITREQUEST = _descriptor.Descriptor(
  name='splitRequest',
  full_name='nlp.split.splitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='nlp.split.splitRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='nlp.split.splitRequest.params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=102,
)


_SPLITRESPONSE = _descriptor.Descriptor(
  name='splitResponse',
  full_name='nlp.split.splitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='nlp.split.splitResponse.word', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='nlp.split.splitResponse.pos', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=146,
)


_SPLITPARAMS = _descriptor.Descriptor(
  name='SplitParams',
  full_name='nlp.split.SplitParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keep_punc', full_name='nlp.split.SplitParams.keep_punc', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eng_word_len_threshold', full_name='nlp.split.SplitParams.eng_word_len_threshold', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_pos', full_name='nlp.split.SplitParams.need_pos', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_rec_nr', full_name='nlp.split.SplitParams.auto_rec_nr', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rec_long_entity', full_name='nlp.split.SplitParams.rec_long_entity', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rec_ambiguous_entity', full_name='nlp.split.SplitParams.rec_ambiguous_entity', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_term_weight', full_name='nlp.split.SplitParams.need_term_weight', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quotation_entity_len_threshold', full_name='nlp.split.SplitParams.quotation_entity_len_threshold', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recognizer_entity', full_name='nlp.split.SplitParams.recognizer_entity', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quotation_common_word_len_threshold', full_name='nlp.split.SplitParams.quotation_common_word_len_threshold', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=498,
)

_SPLITREQUEST.fields_by_name['params'].message_type = _SPLITPARAMS
DESCRIPTOR.message_types_by_name['splitRequest'] = _SPLITREQUEST
DESCRIPTOR.message_types_by_name['splitResponse'] = _SPLITRESPONSE
DESCRIPTOR.message_types_by_name['SplitParams'] = _SPLITPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

splitRequest = _reflection.GeneratedProtocolMessageType('splitRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPLITREQUEST,
  __module__ = 'SentenceSplit_pb2'
  # @@protoc_insertion_point(class_scope:nlp.split.splitRequest)
  ))
_sym_db.RegisterMessage(splitRequest)

splitResponse = _reflection.GeneratedProtocolMessageType('splitResponse', (_message.Message,), dict(
  DESCRIPTOR = _SPLITRESPONSE,
  __module__ = 'SentenceSplit_pb2'
  # @@protoc_insertion_point(class_scope:nlp.split.splitResponse)
  ))
_sym_db.RegisterMessage(splitResponse)

SplitParams = _reflection.GeneratedProtocolMessageType('SplitParams', (_message.Message,), dict(
  DESCRIPTOR = _SPLITPARAMS,
  __module__ = 'SentenceSplit_pb2'
  # @@protoc_insertion_point(class_scope:nlp.split.SplitParams)
  ))
_sym_db.RegisterMessage(SplitParams)



_SEND = _descriptor.ServiceDescriptor(
  name='send',
  full_name='nlp.split.send',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=500,
  serialized_end=568,
  methods=[
  _descriptor.MethodDescriptor(
    name='split',
    full_name='nlp.split.send.split',
    index=0,
    containing_service=None,
    input_type=_SPLITREQUEST,
    output_type=_SPLITRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEND)

DESCRIPTOR.services_by_name['send'] = _SEND

# @@protoc_insertion_point(module_scope)
